// Code generated by jrpc. DO NOT EDIT.

package dmxdef

import (
	context "context"

	rpc "github.com/jakewright/home-automation/libraries/go/rpc"
)

// Do performs the request
func (m *GetDeviceRequest) Do(ctx context.Context) (*GetDeviceResponse, error) {
	req := &rpc.Request{
		Method: "GET",
		URL:    "service.dmx/device",
		Body:   m,
	}

	rsp := &GetDeviceResponse{}
	_, err := rpc.Do(ctx, req, rsp)
	return rsp, err
}

// Do performs the request
func (m *UpdateDeviceRequest) Do(ctx context.Context) (*UpdateDeviceResponse, error) {
	req := &rpc.Request{
		Method: "PATCH",
		URL:    "service.dmx/device",
		Body:   m,
	}

	rsp := &UpdateDeviceResponse{}
	_, err := rpc.Do(ctx, req, rsp)
	return rsp, err
}
