// Code generated by protoc-gen-jrpc. DO NOT EDIT.

package deviceregistryproto

import  "github.com/jakewright/home-automation/libraries/go/rpc"

func (r *BarRequest) Do() (*BarResponse, error) {
	req := rpc.Request{
		Method: "GET",
		URL:    "service.device-registry/foo",
		Body:   r,
	}

	var rsp *BarResponse

	_, err := rpc.Do(req, &rsp)
	if err != nil {
		return nil, err
	}

	return rsp, nil
}
