// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/jakewright/home-automation/tools/protoc-gen-jrpc/proto/jrpc.proto

package jrpcproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Router struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Router) Reset()         { *m = Router{} }
func (m *Router) String() string { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()    {}
func (*Router) Descriptor() ([]byte, []int) {
	return fileDescriptor_174557e077ca7de7, []int{0}
}

func (m *Router) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Router.Unmarshal(m, b)
}
func (m *Router) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Router.Marshal(b, m, deterministic)
}
func (m *Router) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Router.Merge(m, src)
}
func (m *Router) XXX_Size() int {
	return xxx_messageInfo_Router.Size(m)
}
func (m *Router) XXX_DiscardUnknown() {
	xxx_messageInfo_Router.DiscardUnknown(m)
}

var xxx_messageInfo_Router proto.InternalMessageInfo

func (m *Router) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Handler struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_174557e077ca7de7, []int{1}
}

func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (m *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(m, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

func (m *Handler) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Handler) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

var E_Router = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*Router)(nil),
	Field:         50000,
	Name:          "router",
	Tag:           "bytes,50000,opt,name=router",
	Filename:      "github.com/jakewright/home-automation/tools/protoc-gen-jrpc/proto/jrpc.proto",
}

var E_Handler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Handler)(nil),
	Field:         51000,
	Name:          "handler",
	Tag:           "bytes,51000,opt,name=handler",
	Filename:      "github.com/jakewright/home-automation/tools/protoc-gen-jrpc/proto/jrpc.proto",
}

var E_Time = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         52000,
	Name:          "time",
	Tag:           "varint,52000,opt,name=time",
	Filename:      "github.com/jakewright/home-automation/tools/protoc-gen-jrpc/proto/jrpc.proto",
}

func init() {
	proto.RegisterType((*Router)(nil), "Router")
	proto.RegisterType((*Handler)(nil), "Handler")
	proto.RegisterExtension(E_Router)
	proto.RegisterExtension(E_Handler)
	proto.RegisterExtension(E_Time)
}

func init() {
	proto.RegisterFile("github.com/jakewright/home-automation/tools/protoc-gen-jrpc/proto/jrpc.proto", fileDescriptor_174557e077ca7de7)
}

var fileDescriptor_174557e077ca7de7 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x55, 0xa8, 0xd2, 0x62, 0xb6, 0x0c, 0xa8, 0x42, 0xfc, 0x44, 0x9d, 0xba, 0xc4, 0x96,
	0xa8, 0x58, 0xc2, 0x56, 0x21, 0x84, 0x04, 0x15, 0x52, 0xd8, 0xd8, 0xdc, 0xe4, 0x12, 0xbb, 0xc4,
	0xb9, 0x91, 0x73, 0x03, 0x6f, 0xc0, 0xc8, 0xc8, 0xcc, 0x63, 0xf0, 0x18, 0x3c, 0x12, 0x72, 0x9c,
	0xb0, 0x74, 0x64, 0xf2, 0xb9, 0xf2, 0x3d, 0xdf, 0x39, 0x96, 0xd9, 0x7d, 0xa1, 0x49, 0xb5, 0x1b,
	0x9e, 0xa1, 0x11, 0x5b, 0xf9, 0x02, 0x6f, 0x56, 0x17, 0x8a, 0x84, 0x42, 0x03, 0xb1, 0x6c, 0x09,
	0x8d, 0x24, 0x8d, 0x95, 0x20, 0xc4, 0xb2, 0x11, 0xb5, 0x45, 0xc2, 0x2c, 0x2e, 0xa0, 0x8a, 0xb7,
	0xb6, 0xce, 0xfc, 0x2c, 0x9c, 0xe4, 0x9d, 0x3c, 0x8e, 0x0a, 0xc4, 0xa2, 0x04, 0x7f, 0xb1, 0x69,
	0x9f, 0x45, 0x0e, 0x4d, 0x66, 0x75, 0x4d, 0x68, 0xfd, 0xc6, 0xfc, 0x84, 0x05, 0x29, 0xb6, 0x04,
	0x36, 0x0c, 0xd9, 0xb8, 0x92, 0x06, 0x66, 0xa3, 0x68, 0xb4, 0x38, 0x48, 0x3b, 0x3d, 0xbf, 0x64,
	0x93, 0x5b, 0x59, 0xe5, 0x25, 0xd8, 0xf0, 0x88, 0x05, 0x06, 0x48, 0x61, 0xde, 0x2f, 0xf4, 0x93,
	0xb3, 0xd5, 0x92, 0xd4, 0x6c, 0xcf, 0xdb, 0x9c, 0x4e, 0x56, 0x2c, 0xb0, 0x1e, 0x7a, 0xce, 0x7d,
	0x03, 0x3e, 0x34, 0xe0, 0x8f, 0x60, 0x5f, 0x75, 0x06, 0x0f, 0xb5, 0x7b, 0x47, 0x33, 0xfb, 0x79,
	0xdf, 0x8f, 0x46, 0x8b, 0xc3, 0x8b, 0x09, 0xf7, 0x35, 0xd2, 0xde, 0x99, 0x5c, 0xb3, 0x89, 0xea,
	0xa3, 0xcf, 0x76, 0x20, 0xeb, 0x2e, 0x7b, 0x60, 0x7c, 0x7f, 0x78, 0xc6, 0x94, 0xf7, 0x65, 0xd3,
	0xc1, 0x9a, 0x2c, 0xd9, 0x98, 0xb4, 0x81, 0xf0, 0x74, 0x07, 0x71, 0xa3, 0xa1, 0xfc, 0x23, 0x7c,
	0x7d, 0x3a, 0xc2, 0x34, 0xed, 0x96, 0x57, 0xeb, 0xa7, 0xbb, 0x7f, 0xff, 0xc2, 0x95, 0x93, 0x3e,
	0x2c, 0xe8, 0x8e, 0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0xe9, 0xd8, 0x43, 0xdb, 0x01,
	0x00, 0x00,
}
