// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tools/protoc-gen-jrpc/proto/jrpc.proto

package jrpcproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Router struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Router) Reset()         { *m = Router{} }
func (m *Router) String() string { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()    {}
func (*Router) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eca44b7035c5f18, []int{0}
}

func (m *Router) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Router.Unmarshal(m, b)
}
func (m *Router) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Router.Marshal(b, m, deterministic)
}
func (m *Router) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Router.Merge(m, src)
}
func (m *Router) XXX_Size() int {
	return xxx_messageInfo_Router.Size(m)
}
func (m *Router) XXX_DiscardUnknown() {
	xxx_messageInfo_Router.DiscardUnknown(m)
}

var xxx_messageInfo_Router proto.InternalMessageInfo

func (m *Router) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Handler struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eca44b7035c5f18, []int{1}
}

func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (m *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(m, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

func (m *Handler) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Handler) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

var E_Router = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*Router)(nil),
	Field:         50000,
	Name:          "jrpcproto.router",
	Tag:           "bytes,50000,opt,name=router",
	Filename:      "tools/protoc-gen-jrpc/proto/jrpc.proto",
}

var E_Handler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Handler)(nil),
	Field:         51000,
	Name:          "jrpcproto.handler",
	Tag:           "bytes,51000,opt,name=handler",
	Filename:      "tools/protoc-gen-jrpc/proto/jrpc.proto",
}

func init() {
	proto.RegisterType((*Router)(nil), "jrpcproto.Router")
	proto.RegisterType((*Handler)(nil), "jrpcproto.Handler")
	proto.RegisterExtension(E_Router)
	proto.RegisterExtension(E_Handler)
}

func init() {
	proto.RegisterFile("tools/protoc-gen-jrpc/proto/jrpc.proto", fileDescriptor_2eca44b7035c5f18)
}

var fileDescriptor_2eca44b7035c5f18 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbd, 0x4a, 0xc4, 0x40,
	0x10, 0x80, 0x89, 0x4a, 0x8e, 0x5b, 0x2b, 0x53, 0x48, 0x10, 0xd1, 0x70, 0x85, 0x5c, 0x93, 0x5d,
	0x50, 0x6c, 0xce, 0xce, 0x4a, 0xd0, 0x53, 0x88, 0x9d, 0xdd, 0x26, 0x19, 0xb3, 0x39, 0x93, 0x4c,
	0xd8, 0x4c, 0xf4, 0x0d, 0x2c, 0x7d, 0x1e, 0x1f, 0xc3, 0x47, 0x92, 0xfd, 0xc9, 0x21, 0x08, 0x57,
	0xe5, 0x1b, 0x98, 0xf9, 0xf8, 0xb2, 0xec, 0x82, 0x10, 0x9b, 0x41, 0xf4, 0x1a, 0x09, 0x8b, 0xb4,
	0x82, 0x2e, 0xdd, 0xe8, 0xbe, 0x70, 0xb3, 0x30, 0xc8, 0x2d, 0x46, 0x73, 0xc3, 0x16, 0x4f, 0x92,
	0x0a, 0xb1, 0x6a, 0xc0, 0xed, 0xe4, 0xe3, 0xab, 0x28, 0x61, 0x28, 0x74, 0xdd, 0x13, 0x6a, 0xb7,
	0xbc, 0x38, 0x65, 0x61, 0x86, 0x23, 0x81, 0x8e, 0x22, 0x76, 0xd0, 0xc9, 0x16, 0xe2, 0x20, 0x09,
	0x96, 0xf3, 0xcc, 0xf2, 0xe2, 0x9a, 0xcd, 0xee, 0x64, 0x57, 0x36, 0xa0, 0xa3, 0x63, 0x16, 0xb6,
	0x40, 0x0a, 0x4b, 0xbf, 0xe0, 0x27, 0x73, 0xd6, 0x4b, 0x52, 0xf1, 0x9e, 0x3b, 0x33, 0xbc, 0x7a,
	0x60, 0xa1, 0x76, 0xd2, 0x73, 0xee, 0x0a, 0xf8, 0x54, 0xc0, 0x9f, 0x41, 0xbf, 0xd7, 0x05, 0x3c,
	0xf5, 0x54, 0x63, 0x37, 0xc4, 0x3f, 0x9f, 0xfb, 0x49, 0xb0, 0x3c, 0xbc, 0x3c, 0xe2, 0xdb, 0x6a,
	0xee, 0x82, 0x32, 0xef, 0x58, 0x3d, 0xb2, 0x99, 0xf2, 0x11, 0x67, 0xff, 0x74, 0x6b, 0x5b, 0x31,
	0xd9, 0xbe, 0xbf, 0x9c, 0x2d, 0xfa, 0x63, 0xf3, 0x3f, 0x90, 0x4d, 0x92, 0xdb, 0xf5, 0xcb, 0x7d,
	0x55, 0x93, 0x1a, 0x73, 0x5e, 0x60, 0x2b, 0x36, 0xf2, 0x0d, 0x3e, 0x74, 0x5d, 0x29, 0x12, 0x0a,
	0x5b, 0x48, 0xe5, 0x48, 0xd8, 0x4a, 0xa3, 0x13, 0x3b, 0xde, 0xfb, 0x66, 0xeb, 0xcf, 0x43, 0xfb,
	0xb9, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x3a, 0x1e, 0x2b, 0x9f, 0x01, 0x00, 0x00,
}
