// Code generated by jrpc. DO NOT EDIT.

package dmxproxydef

import (
	oops "github.com/jakewright/home-automation/libraries/go/oops"
)

// SetRequest is defined in the .def file
type SetRequest struct {
	Universe uint8   `json:"universe"`
	Values   []uint8 `json:"values"`
}

// SetResponse is defined in the .def file
type SetResponse struct {
}

// Validate returns an error if any of the fields have bad values
func (m *SetRequest) Validate() error {
	if m.Universe == 0 {
		return oops.BadRequest("field 'universe' is required")
	}
	if len(m.Values) == 0 {
		return oops.BadRequest("field 'values' is required")
	}
	return nil
}

// Validate returns an error if any of the fields have bad values
func (m *SetResponse) Validate() error {
	return nil
}
