// Code generated by jrpc. DO NOT EDIT.

package handler

import (
	context "context"

	"github.com/jakewright/home-automation/libraries/go/bootstrap"
	router "github.com/jakewright/home-automation/libraries/go/router"
	taxi "github.com/jakewright/home-automation/libraries/go/taxi"
	def "github.com/jakewright/home-automation/services/device-registry/def"
)

type handler interface {
	GetDevice(ctx context.Context, body *def.GetDeviceRequest) (*def.GetDeviceResponse, error)
	ListDevices(ctx context.Context, body *def.ListDevicesRequest) (*def.ListDevicesResponse, error)
	GetRoom(ctx context.Context, body *def.GetRoomRequest) (*def.GetRoomResponse, error)
	ListRooms(ctx context.Context, body *def.ListRoomsRequest) (*def.ListRoomsResponse, error)
}

// NewRouter creates a new router for the service
func NewRouter(svc *bootstrap.Service, h handler) *router.Router {
	r := router.New(svc)

	r.RegisterHandler("GET", "/device", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.GetDeviceRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.GetDevice(ctx, body)
	})

	r.RegisterHandler("GET", "/devices", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.ListDevicesRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.ListDevices(ctx, body)
	})

	r.RegisterHandler("GET", "/room", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.GetRoomRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.GetRoom(ctx, body)
	})

	r.RegisterHandler("GET", "/rooms", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.ListRoomsRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.ListRooms(ctx, body)
	})

	return r
}
