// Code generated by jrpc. DO NOT EDIT.

package handler

import (
	context "context"
	http "net/http"

	network "github.com/jakewright/home-automation/libraries/go/network"
	oops "github.com/jakewright/home-automation/libraries/go/oops"
	router "github.com/jakewright/home-automation/libraries/go/router"
	slog "github.com/jakewright/home-automation/libraries/go/slog"
	def "github.com/jakewright/home-automation/service.device-registry/def"
)

type controller interface {
	GetDevice(*request, *def.GetDeviceRequest) (*def.GetDeviceResponse, error)
	ListDevices(*request, *def.ListDevicesRequest) (*def.ListDevicesResponse, error)
	GetRoom(*request, *def.GetRoomRequest) (*def.GetRoomResponse, error)
	ListRooms(*request, *def.ListRoomsRequest) (*def.ListRoomsResponse, error)
}

type request struct {
	context.Context
	*http.Request
}

// NewRouter returns a router with appropriate handlers set
func NewRouter(c controller) *router.Router {
	r := router.New()

	r.Handle("GET", "/device", func(w http.ResponseWriter, r *http.Request) {
		body := &def.GetDeviceRequest{}
		if err := network.DecodeRequest(r, body); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		req := &request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := c.GetDevice(req, body)
		if err != nil {
			err = oops.WithMessage(err, "failed to handle request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		network.WriteJSONResponse(w, rsp)
	})

	r.Handle("GET", "/devices", func(w http.ResponseWriter, r *http.Request) {
		body := &def.ListDevicesRequest{}
		if err := network.DecodeRequest(r, body); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		req := &request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := c.ListDevices(req, body)
		if err != nil {
			err = oops.WithMessage(err, "failed to handle request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		network.WriteJSONResponse(w, rsp)
	})

	r.Handle("GET", "/room", func(w http.ResponseWriter, r *http.Request) {
		body := &def.GetRoomRequest{}
		if err := network.DecodeRequest(r, body); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		req := &request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := c.GetRoom(req, body)
		if err != nil {
			err = oops.WithMessage(err, "failed to handle request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		network.WriteJSONResponse(w, rsp)
	})

	r.Handle("GET", "/rooms", func(w http.ResponseWriter, r *http.Request) {
		body := &def.ListRoomsRequest{}
		if err := network.DecodeRequest(r, body); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = oops.Wrap(err, oops.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		req := &request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := c.ListRooms(req, body)
		if err != nil {
			err = oops.WithMessage(err, "failed to handle request")
			slog.Error(err)
			network.WriteJSONResponse(w, err)
			return
		}

		network.WriteJSONResponse(w, rsp)
	})

	return r
}
