// Code generated by jrpc. DO NOT EDIT.

package handler

import (
	context "context"
	http "net/http"

	"github.com/jakewright/home-automation/libraries/go/errors"
	"github.com/jakewright/home-automation/libraries/go/request"
	"github.com/jakewright/home-automation/libraries/go/response"
	"github.com/jakewright/home-automation/libraries/go/router"
	"github.com/jakewright/home-automation/libraries/go/slog"
	def "github.com/jakewright/home-automation/service.device-registry/def"
)

// DeviceRegistryRouter wraps router.Router to provide a convenient way to set handlers
type DeviceRegistryRouter struct {
	*router.Router
	GetDevice   func(*Request, *def.GetDeviceRequest) (*def.GetDeviceResponse, error)
	ListDevices func(*Request, *def.ListDevicesRequest) (*def.ListDevicesResponse, error)
	GetRoom     func(*Request, *def.GetRoomRequest) (*def.GetRoomResponse, error)
	ListRooms   func(*Request, *def.ListRoomsRequest) (*def.ListRoomsResponse, error)
}

// NewRouter returns a router that is ready to add handlers to
func NewRouter() *DeviceRegistryRouter {
	rr := &DeviceRegistryRouter{
		Router: router.New(),
	}

	rr.Router.Handle("GET", "/device", func(w http.ResponseWriter, r *http.Request) {
		if rr.GetDevice == nil {
			slog.Panicf("No handler exists for GET /device")
		}

		body := &def.GetDeviceRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.GetDevice(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	rr.Router.Handle("GET", "/devices", func(w http.ResponseWriter, r *http.Request) {
		if rr.ListDevices == nil {
			slog.Panicf("No handler exists for GET /devices")
		}

		body := &def.ListDevicesRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.ListDevices(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	rr.Router.Handle("GET", "/room", func(w http.ResponseWriter, r *http.Request) {
		if rr.GetRoom == nil {
			slog.Panicf("No handler exists for GET /room")
		}

		body := &def.GetRoomRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.GetRoom(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	rr.Router.Handle("GET", "/rooms", func(w http.ResponseWriter, r *http.Request) {
		if rr.ListRooms == nil {
			slog.Panicf("No handler exists for GET /rooms")
		}

		body := &def.ListRoomsRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.ListRooms(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	return rr
}

type Request struct {
	context.Context
	*http.Request
}
