// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/jakewright/home-automation/service.user/proto/user.proto

package userproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/jakewright/home-automation/tools/protoc-gen-jrpc/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ebed64d6eeb07d, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetUserRequest struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ebed64d6eeb07d, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ebed64d6eeb07d, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "userproto.User")
	proto.RegisterType((*GetUserRequest)(nil), "userproto.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "userproto.GetUserResponse")
}

func init() {
	proto.RegisterFile("github.com/jakewright/home-automation/service.user/proto/user.proto", fileDescriptor_b8ebed64d6eeb07d)
}

var fileDescriptor_b8ebed64d6eeb07d = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x25, 0xfd, 0xd2, 0xf6, 0xeb, 0x54, 0x5b, 0x58, 0x10, 0xd3, 0x9c, 0x4a, 0xbc, 0xd4, 0x43,
	0x13, 0xa8, 0xe0, 0xc5, 0x53, 0xab, 0x52, 0x04, 0x4f, 0x51, 0x11, 0xbc, 0x94, 0x34, 0x19, 0xda,
	0x54, 0x93, 0x8d, 0xbb, 0x13, 0x05, 0x8f, 0xfe, 0x27, 0xef, 0xd2, 0x5f, 0x24, 0xf4, 0x0f, 0xc8,
	0x6e, 0x62, 0xa8, 0xe0, 0x41, 0x3c, 0xe5, 0xcd, 0xbc, 0x97, 0x37, 0x6f, 0x67, 0xe0, 0x74, 0x11,
	0xd3, 0x32, 0x9f, 0xbb, 0x21, 0x4f, 0xbc, 0x55, 0x70, 0x8f, 0xcf, 0x22, 0x5e, 0x2c, 0xc9, 0x5b,
	0xf2, 0x04, 0x87, 0x41, 0x4e, 0x3c, 0x09, 0x28, 0xe6, 0xa9, 0x27, 0x51, 0x3c, 0xc5, 0x21, 0xba,
	0xb9, 0x44, 0xe1, 0x65, 0x82, 0x13, 0xf7, 0x14, 0x74, 0x35, 0x64, 0x2d, 0x85, 0x35, 0xb4, 0x2f,
	0x7f, 0xe7, 0x47, 0x9c, 0x3f, 0xc8, 0xc2, 0x28, 0x1c, 0x2e, 0x30, 0x1d, 0xae, 0x44, 0x16, 0x96,
	0xc6, 0x0a, 0x16, 0xc6, 0x0e, 0x81, 0x79, 0x23, 0x51, 0xb0, 0x0e, 0xd4, 0xe2, 0xc8, 0x32, 0xfa,
	0xc6, 0x60, 0xd7, 0xaf, 0xc5, 0x11, 0x63, 0x60, 0xa6, 0x41, 0x82, 0x56, 0xad, 0x6f, 0x0c, 0x5a,
	0xbe, 0xc6, 0xec, 0x00, 0x20, 0x14, 0x18, 0x10, 0x46, 0xb3, 0x80, 0x2c, 0x53, 0x31, 0x13, 0xf3,
	0xfd, 0xa3, 0x67, 0xf8, 0xad, 0xb2, 0x3f, 0x26, 0x25, 0xca, 0xb3, 0xe8, 0x4b, 0x54, 0xdf, 0x16,
	0x95, 0xfd, 0x31, 0x39, 0x87, 0xd0, 0x99, 0x22, 0xa9, 0xc1, 0x3e, 0x3e, 0xe6, 0x28, 0x89, 0xed,
	0x43, 0x53, 0x3d, 0x71, 0x56, 0x85, 0x68, 0xa8, 0xf2, 0x22, 0x72, 0x8e, 0xa1, 0x5b, 0x49, 0x65,
	0xc6, 0x53, 0xa9, 0x72, 0x98, 0x8a, 0xd4, 0xc2, 0xf6, 0xa8, 0xeb, 0x56, 0xbb, 0x71, 0xb5, 0x4c,
	0x93, 0xa3, 0x17, 0x68, 0xab, 0xea, 0xaa, 0x58, 0x2b, 0xbb, 0x85, 0x66, 0x69, 0xc3, 0x7a, 0x5b,
	0x3f, 0x7c, 0x4f, 0x61, 0xdb, 0x3f, 0x51, 0xc5, 0x54, 0x67, 0x6f, 0xbd, 0xb1, 0xea, 0xf0, 0x6f,
	0x7a, 0x7e, 0xbd, 0xde, 0x58, 0xff, 0x59, 0x43, 0x9f, 0xc7, 0xb3, 0xd9, 0xeb, 0x9b, 0xd5, 0x81,
	0x9d, 0xed, 0xf3, 0x4d, 0xce, 0xee, 0x26, 0x7f, 0x3d, 0xfa, 0x49, 0x15, 0x60, 0xde, 0xd0, 0x9f,
	0xa3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xfe, 0xfa, 0x0b, 0x41, 0x02, 0x00, 0x00,
}
