// Code generated by jrpc. DO NOT EDIT.

package scenedef

import (
	context "context"

	rpc "github.com/jakewright/home-automation/libraries/go/rpc"
)

// Do performs the request
func (m *CreateSceneRequest) Request() *rpc.Request {
	return &rpc.Request{
		Method: "POST",
		URL:    "service.scene/scenes",
		Body:   m,
	}
}

func (m *CreateSceneRequest) Do(ctx context.Context) (*CreateSceneResponse, error) {
	rsp := &CreateSceneResponse{}
	_, err := rpc.Do(ctx, m.Request(), rsp)
	return rsp, err
}

// Do performs the request
func (m *ReadSceneRequest) Request() *rpc.Request {
	return &rpc.Request{
		Method: "GET",
		URL:    "service.scene/scene",
		Body:   m,
	}
}

func (m *ReadSceneRequest) Do(ctx context.Context) (*ReadSceneResponse, error) {
	rsp := &ReadSceneResponse{}
	_, err := rpc.Do(ctx, m.Request(), rsp)
	return rsp, err
}

// Do performs the request
func (m *ListScenesRequest) Request() *rpc.Request {
	return &rpc.Request{
		Method: "GET",
		URL:    "service.scene/scenes",
		Body:   m,
	}
}

func (m *ListScenesRequest) Do(ctx context.Context) (*ListScenesResponse, error) {
	rsp := &ListScenesResponse{}
	_, err := rpc.Do(ctx, m.Request(), rsp)
	return rsp, err
}

// Do performs the request
func (m *DeleteSceneRequest) Request() *rpc.Request {
	return &rpc.Request{
		Method: "DELETE",
		URL:    "service.scene/scene",
		Body:   m,
	}
}

func (m *DeleteSceneRequest) Do(ctx context.Context) (*DeleteSceneResponse, error) {
	rsp := &DeleteSceneResponse{}
	_, err := rpc.Do(ctx, m.Request(), rsp)
	return rsp, err
}

// Do performs the request
func (m *SetSceneRequest) Request() *rpc.Request {
	return &rpc.Request{
		Method: "POST",
		URL:    "service.scene/scene/set",
		Body:   m,
	}
}

func (m *SetSceneRequest) Do(ctx context.Context) (*SetSceneResponse, error) {
	rsp := &SetSceneResponse{}
	_, err := rpc.Do(ctx, m.Request(), rsp)
	return rsp, err
}
