// Code generated by jrpc. DO NOT EDIT.

package scenedef

import (
	rpc "github.com/jakewright/home-automation/libraries/go/rpc"
)

// Do performs the request
func (m *CreateSceneRequest) Do() (*CreateSceneResponse, error) {
	req := &rpc.Request{
		Method: "POST",
		URL:    "service.scene/scenes",
		Body:   m,
	}

	rsp := &CreateSceneResponse{}
	_, err := rpc.Do(req, rsp)
	return rsp, err
}

// Do performs the request
func (m *ReadSceneRequest) Do() (*ReadSceneResponse, error) {
	req := &rpc.Request{
		Method: "GET",
		URL:    "service.scene/scene",
		Body:   m,
	}

	rsp := &ReadSceneResponse{}
	_, err := rpc.Do(req, rsp)
	return rsp, err
}

// Do performs the request
func (m *ListScenesRequest) Do() (*ListScenesResponse, error) {
	req := &rpc.Request{
		Method: "GET",
		URL:    "service.scene/scenes",
		Body:   m,
	}

	rsp := &ListScenesResponse{}
	_, err := rpc.Do(req, rsp)
	return rsp, err
}

// Do performs the request
func (m *DeleteSceneRequest) Do() (*DeleteSceneResponse, error) {
	req := &rpc.Request{
		Method: "DELETE",
		URL:    "service.scene/scene",
		Body:   m,
	}

	rsp := &DeleteSceneResponse{}
	_, err := rpc.Do(req, rsp)
	return rsp, err
}

// Do performs the request
func (m *SetSceneRequest) Do() (*SetSceneResponse, error) {
	req := &rpc.Request{
		Method: "POST",
		URL:    "service.scene/scene/set",
		Body:   m,
	}

	rsp := &SetSceneResponse{}
	_, err := rpc.Do(req, rsp)
	return rsp, err
}
