// Code generated by protoc-gen-jrpc. DO NOT EDIT.

package sceneproto

import "github.com/jakewright/home-automation/libraries/go/firehose"

// Publish publishes the event to the Firehose
func (e *SetSceneEvent) Publish() error {
	if err := e.Validate(); err != nil {
		return err
	}

	return firehose.Publish("set-scene", e)
}
