// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/jakewright/home-automation/service.scene/proto/scene.proto

package sceneproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/jakewright/home-automation/tools/protoc-gen-jrpc/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSceneRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSceneRequest) Reset()         { *m = CreateSceneRequest{} }
func (m *CreateSceneRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSceneRequest) ProtoMessage()    {}
func (*CreateSceneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e138e95ef801d2a9, []int{0}
}

func (m *CreateSceneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSceneRequest.Unmarshal(m, b)
}
func (m *CreateSceneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSceneRequest.Marshal(b, m, deterministic)
}
func (m *CreateSceneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSceneRequest.Merge(m, src)
}
func (m *CreateSceneRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSceneRequest.Size(m)
}
func (m *CreateSceneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSceneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSceneRequest proto.InternalMessageInfo

func (m *CreateSceneRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateSceneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSceneResponse) Reset()         { *m = CreateSceneResponse{} }
func (m *CreateSceneResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSceneResponse) ProtoMessage()    {}
func (*CreateSceneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e138e95ef801d2a9, []int{1}
}

func (m *CreateSceneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSceneResponse.Unmarshal(m, b)
}
func (m *CreateSceneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSceneResponse.Marshal(b, m, deterministic)
}
func (m *CreateSceneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSceneResponse.Merge(m, src)
}
func (m *CreateSceneResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSceneResponse.Size(m)
}
func (m *CreateSceneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSceneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSceneResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateSceneRequest)(nil), "sceneproto.CreateSceneRequest")
	proto.RegisterType((*CreateSceneResponse)(nil), "sceneproto.CreateSceneResponse")
}

func init() {
	proto.RegisterFile("github.com/jakewright/home-automation/service.scene/proto/scene.proto", fileDescriptor_e138e95ef801d2a9)
}

var fileDescriptor_e138e95ef801d2a9 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4a, 0xcc, 0x4e, 0x2d, 0x2f, 0xca, 0x4c, 0xcf,
	0x28, 0xd1, 0xcf, 0xc8, 0xcf, 0x4d, 0xd5, 0x4d, 0x2c, 0x2d, 0xc9, 0xcf, 0x4d, 0x2c, 0xc9, 0xcc,
	0xcf, 0xd3, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x4e, 0x4e, 0xcd, 0x4b, 0xd5,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x07, 0xb3, 0xf5, 0xc0, 0x6c, 0x21, 0x2e, 0x30, 0x07, 0xcc,
	0x96, 0xf2, 0x21, 0xce, 0xc8, 0x92, 0xfc, 0xfc, 0x9c, 0x62, 0x88, 0x51, 0xc9, 0xba, 0xe9, 0xa9,
	0x79, 0xba, 0x59, 0x45, 0x05, 0xc9, 0x50, 0xa3, 0x41, 0x4c, 0x88, 0xc9, 0x4a, 0x1a, 0x5c, 0x42,
	0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0xc1, 0x20, 0x1b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x25, 0x51, 0x2e, 0x61, 0x14, 0x95, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x46, 0xad, 0x8c,
	0x5c, 0xac, 0x60, 0x11, 0xa1, 0x74, 0x2e, 0x6e, 0x24, 0x05, 0x42, 0x72, 0x7a, 0x08, 0x47, 0xeb,
	0x61, 0xda, 0x21, 0x25, 0x8f, 0x53, 0x1e, 0x62, 0xb2, 0x92, 0xf8, 0xa1, 0xcf, 0x12, 0x6c, 0x5c,
	0x2c, 0x01, 0xfe, 0xc1, 0x21, 0x87, 0x3e, 0x4b, 0x70, 0x0a, 0xb1, 0x43, 0x82, 0xa4, 0x58, 0x4a,
	0xb8, 0x69, 0xab, 0x04, 0x3f, 0x17, 0x2f, 0x4a, 0xa0, 0x39, 0xb9, 0x45, 0xb9, 0x90, 0x1d, 0xd6,
	0xd6, 0x08, 0x97, 0x24, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0x24,
	0x28, 0x6f, 0xba, 0x01, 0x00, 0x00,
}
