// Code generated by protoc-gen-jrpc. DO NOT EDIT.

package sceneproto

import (
	"net/http"

	"github.com/jakewright/home-automation/libraries/go/request"
	"github.com/jakewright/home-automation/libraries/go/response"
	"github.com/jakewright/home-automation/libraries/go/router"
	"github.com/jakewright/home-automation/libraries/go/rpc"
	"github.com/jakewright/home-automation/libraries/go/slog"
)

// sceneRouter wraps router.Router to provide a convenient way to set handlers
type sceneRouter struct {
	*router.Router
	CreateScene func(*CreateSceneRequest) (*CreateSceneResponse, error)
	DeleteScene func(*DeleteSceneRequest) (*DeleteSceneResponse, error)
}

// NewRouter returns a router that is ready to add handlers to
func NewRouter() *sceneRouter {
	rr := &sceneRouter{
		Router: router.New(),
	}

	rr.Router.Handle("POST", "/scenes", func(w http.ResponseWriter, r *http.Request) {
		body := &CreateSceneRequest{}
		if err := request.Decode(r, body); err != nil {
			response.WriteJSON(w, err)
			return
		}

		if rr.CreateScene == nil {
			slog.Panic("No handler exists for POST service.scene/scenes")
		}

		rsp, err := rr.CreateScene(body)
		if err != nil {
			slog.Error("Failed to handle request: %v", err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	rr.Router.Handle("DELETE", "/scene", func(w http.ResponseWriter, r *http.Request) {
		body := &DeleteSceneRequest{}
		if err := request.Decode(r, body); err != nil {
			response.WriteJSON(w, err)
			return
		}

		if rr.DeleteScene == nil {
			slog.Panic("No handler exists for DELETE service.scene/scene")
		}

		rsp, err := rr.DeleteScene(body)
		if err != nil {
			slog.Error("Failed to handle request: %v", err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	return rr
}

// Do makes performs the request
func (m *CreateSceneRequest) Do() (*CreateSceneResponse, error) {
	req := &rpc.Request{
		Method: "POST",
		URL:    "service.scene/scenes",
		Body:   m,
	}

	rsp := &CreateSceneResponse{}
	_, err := rpc.Do(req, rsp)
	return rsp, err
}

// Do makes performs the request
func (m *DeleteSceneRequest) Do() (*DeleteSceneResponse, error) {
	req := &rpc.Request{
		Method: "DELETE",
		URL:    "service.scene/scene",
		Body:   m,
	}

	rsp := &DeleteSceneResponse{}
	_, err := rpc.Do(req, rsp)
	return rsp, err
}
