// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/jakewright/home-automation/libraries/go/router/proto/router.proto

package routerproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingResponse struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45e2a94659d7ac69, []int{0}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

func init() {
	proto.RegisterType((*PingResponse)(nil), "routerproto.PingResponse")
}

func init() {
	proto.RegisterFile("github.com/jakewright/home-automation/libraries/go/router/proto/router.proto", fileDescriptor_45e2a94659d7ac69)
}

var fileDescriptor_45e2a94659d7ac69 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xf2, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4a, 0xcc, 0x4e, 0x2d, 0x2f, 0xca, 0x4c, 0xcf,
	0x28, 0xd1, 0xcf, 0xc8, 0xcf, 0x4d, 0xd5, 0x4d, 0x2c, 0x2d, 0xc9, 0xcf, 0x4d, 0x2c, 0xc9, 0xcc,
	0xcf, 0xd3, 0xcf, 0xc9, 0x4c, 0x2a, 0x4a, 0x2c, 0xca, 0x4c, 0x2d, 0xd6, 0x4f, 0xcf, 0xd7, 0x2f,
	0xca, 0x2f, 0x2d, 0x49, 0x2d, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0x81, 0x71, 0xf4, 0xc0, 0x1c, 0x21,
	0x6e, 0x08, 0x0f, 0xcc, 0x51, 0x52, 0xe2, 0xe2, 0x09, 0xc8, 0xcc, 0x4b, 0x0f, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe2, 0x62, 0x29, 0xc8, 0xcc, 0x4b, 0x97, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x9d, 0x7c, 0xa3, 0xbc, 0x29, 0x74, 0x80, 0x35, 0x92, 0x95, 0x49,
	0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x04, 0xf7, 0xaf, 0xb0, 0xd6, 0x00, 0x00,
	0x00,
}
