// Code generated by jrpc. DO NOT EDIT.

package userdef

import (
	context "context"
	"testing"

	taxi "github.com/jakewright/home-automation/libraries/go/taxi"
)

// UserService is the public interface of this service
type UserService interface {
	GetUser(ctx context.Context, body *GetUserRequest) *GetUserFuture
	ListUsers(ctx context.Context, body *ListUsersRequest) *ListUsersFuture
}

// GetUserFuture represents an in-flight GetUser request
type GetUserFuture struct {
	done <-chan struct{}
	rsp  *GetUserResponse
	err  error
}

// Wait blocks until the response is ready
func (f *GetUserFuture) Wait() (*GetUserResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// ListUsersFuture represents an in-flight ListUsers request
type ListUsersFuture struct {
	done <-chan struct{}
	rsp  *ListUsersResponse
	err  error
}

// Wait blocks until the response is ready
func (f *ListUsersFuture) Wait() (*ListUsersResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// Client makes requests to this service
type Client struct {
	dispatcher taxi.Dispatcher
}

// Compile-time assertion that the client implements the interface
var _ UserService = (*Client)(nil)

// NewClient returns a new client
func NewClient(dispatcher taxi.Dispatcher) *Client {
	return &Client{
		dispatcher: dispatcher,
	}
}

// GetUser dispatches an RPC to the service
func (c *Client) GetUser(ctx context.Context, body *GetUserRequest) *GetUserFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://user/user",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetUserFuture{
		done: done,
		rsp:  &GetUserResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// ListUsers dispatches an RPC to the service
func (c *Client) ListUsers(ctx context.Context, body *ListUsersRequest) *ListUsersFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://user/users",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &ListUsersFuture{
		done: done,
		rsp:  &ListUsersResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// MockClient can be used in tests
type MockClient struct {
	dispatcher *taxi.MockClient
}

// Compile-time assertion that the mock client implements the interface
var _ UserService = (*MockClient)(nil)

// NewMockClient returns a new mock client
func NewMockClient(ctx context.Context, t *testing.T) *MockClient {
	f := taxi.NewTestFixture(t)

	return &MockClient{
		dispatcher: &taxi.MockClient{Handler: f},
	}
}

// GetUser dispatches an RPC to the mock client
func (c *MockClient) GetUser(ctx context.Context, body *GetUserRequest) *GetUserFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://user/user",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetUserFuture{
		done: done,
		rsp:  &GetUserResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}

// ListUsers dispatches an RPC to the mock client
func (c *MockClient) ListUsers(ctx context.Context, body *ListUsersRequest) *ListUsersFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://user/users",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &ListUsersFuture{
		done: done,
		rsp:  &ListUsersResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}
