package main

import (
	"strings"
	"text/template"

	"github.com/jakewright/home-automation/libraries/go/svcdef"
)

var firehoseTemplate *template.Template

func init() {
	var err error
	firehoseTemplate, err = template.New("firehose_template").Parse(firehoseTemplateText)
	if err != nil {
		panic(err)
	}
}

type event struct {
	TypeName  string
	EventName string
}

type firehoseData struct {
	PackageName string
	PackageDir  string
	Events      []*event
}

const firehoseTemplateText = `// Code generated by jrpc. DO NOT EDIT.

package {{ .PackageName }}

import (
	"encoding/json"

	"github.com/jakewright/home-automation/libraries/go/errors"
	"github.com/jakewright/home-automation/libraries/go/firehose"
)

{{ range .Events }}
	// Publish publishes the event to the Firehose
	func (m *{{ .TypeName }}) Publish() error {
		if err := m.Validate(); err != nil {
			return err
		}

		return firehose.Publish("{{ .EventName }}", m)
	}

	// {{ .TypeName}}Handler implements the necessary functions to be a Firehose handler
	type {{ .TypeName }}Handler func(*{{ .TypeName }}) firehose.Result

	// EventName returns the Firehose channel name
	func (h {{ .TypeName }}Handler) EventName() string {
		return "{{ .EventName }}"
	}

	// HandleEvent handles the Firehose event
	func (h {{ .TypeName }}Handler) HandleEvent(e *firehose.Event) firehose.Result {
		var body {{ .TypeName }}
		if err := json.Unmarshal(e.Payload, &body); err != nil {
			return firehose.Discard(errors.WithMessage(err, "failed to unmarshal payload"))
		}
		return h(&body)
	}
{{ end }}
`

func createFirehoseTemplateData(opts *options, file *svcdef.File) (*firehoseData, error) {
	var events []*event
	for _, m := range file.Messages {
		eventName, ok := m.Options["event_name"].(string)
		if !ok {
			continue
		}

		typeName := strings.ReplaceAll(m.QualifiedName, ".", "_")

		events = append(events, &event{
			TypeName:  typeName,
			EventName: eventName,
		})
	}

	return &firehoseData{
		PackageName: externalPackageName(opts),
		PackageDir:  packageDirExternal,
		Events:      events,
	}, nil
}
