// Code generated by jrpc. DO NOT EDIT.

package deviceregistrydef

import (
	context "context"
	"testing"

	taxi "github.com/jakewright/home-automation/libraries/go/taxi"
)

// DeviceRegistryService is the public interface of this service
type DeviceRegistryService interface {
	GetDevice(ctx context.Context, body *GetDeviceRequest) *GetDeviceFuture
	ListDevices(ctx context.Context, body *ListDevicesRequest) *ListDevicesFuture
	GetRoom(ctx context.Context, body *GetRoomRequest) *GetRoomFuture
	ListRooms(ctx context.Context, body *ListRoomsRequest) *ListRoomsFuture
}

// GetDeviceFuture represents an in-flight GetDevice request
type GetDeviceFuture struct {
	done <-chan struct{}
	rsp  *GetDeviceResponse
	err  error
}

// Wait blocks until the response is ready
func (f *GetDeviceFuture) Wait() (*GetDeviceResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// ListDevicesFuture represents an in-flight ListDevices request
type ListDevicesFuture struct {
	done <-chan struct{}
	rsp  *ListDevicesResponse
	err  error
}

// Wait blocks until the response is ready
func (f *ListDevicesFuture) Wait() (*ListDevicesResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// GetRoomFuture represents an in-flight GetRoom request
type GetRoomFuture struct {
	done <-chan struct{}
	rsp  *GetRoomResponse
	err  error
}

// Wait blocks until the response is ready
func (f *GetRoomFuture) Wait() (*GetRoomResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// ListRoomsFuture represents an in-flight ListRooms request
type ListRoomsFuture struct {
	done <-chan struct{}
	rsp  *ListRoomsResponse
	err  error
}

// Wait blocks until the response is ready
func (f *ListRoomsFuture) Wait() (*ListRoomsResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// Client makes requests to this service
type Client struct {
	dispatcher taxi.Dispatcher
}

// Compile-time assertion that the client implements the interface
var _ DeviceRegistryService = (*Client)(nil)

// NewClient returns a new client
func NewClient(dispatcher taxi.Dispatcher) *Client {
	return &Client{
		dispatcher: dispatcher,
	}
}

// GetDevice dispatches an RPC to the service
func (c *Client) GetDevice(ctx context.Context, body *GetDeviceRequest) *GetDeviceFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/device",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetDeviceFuture{
		done: done,
		rsp:  &GetDeviceResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// ListDevices dispatches an RPC to the service
func (c *Client) ListDevices(ctx context.Context, body *ListDevicesRequest) *ListDevicesFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/devices",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &ListDevicesFuture{
		done: done,
		rsp:  &ListDevicesResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// GetRoom dispatches an RPC to the service
func (c *Client) GetRoom(ctx context.Context, body *GetRoomRequest) *GetRoomFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/room",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetRoomFuture{
		done: done,
		rsp:  &GetRoomResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// ListRooms dispatches an RPC to the service
func (c *Client) ListRooms(ctx context.Context, body *ListRoomsRequest) *ListRoomsFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/rooms",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &ListRoomsFuture{
		done: done,
		rsp:  &ListRoomsResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// MockClient can be used in tests
type MockClient struct {
	dispatcher *taxi.MockClient
}

// Compile-time assertion that the mock client implements the interface
var _ DeviceRegistryService = (*MockClient)(nil)

// NewMockClient returns a new mock client
func NewMockClient(ctx context.Context, t *testing.T) *MockClient {
	f := taxi.NewTestFixture(t)

	return &MockClient{
		dispatcher: &taxi.MockClient{Handler: f},
	}
}

// GetDevice dispatches an RPC to the mock client
func (c *MockClient) GetDevice(ctx context.Context, body *GetDeviceRequest) *GetDeviceFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/device",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetDeviceFuture{
		done: done,
		rsp:  &GetDeviceResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}

// ListDevices dispatches an RPC to the mock client
func (c *MockClient) ListDevices(ctx context.Context, body *ListDevicesRequest) *ListDevicesFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/devices",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &ListDevicesFuture{
		done: done,
		rsp:  &ListDevicesResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}

// GetRoom dispatches an RPC to the mock client
func (c *MockClient) GetRoom(ctx context.Context, body *GetRoomRequest) *GetRoomFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/room",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetRoomFuture{
		done: done,
		rsp:  &GetRoomResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}

// ListRooms dispatches an RPC to the mock client
func (c *MockClient) ListRooms(ctx context.Context, body *ListRoomsRequest) *ListRoomsFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://device-registry/rooms",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &ListRoomsFuture{
		done: done,
		rsp:  &ListRoomsResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}
