// Code generated by jrpc. DO NOT EDIT.

package dummydef

// LogRequest is defined in the .def file
type LogRequest struct {
}

// Validate returns an error if any of the fields have bad values
func (m *LogRequest) Validate() error {
	return nil
}

// LogResponse is defined in the .def file
type LogResponse struct {
}

// Validate returns an error if any of the fields have bad values
func (m *LogResponse) Validate() error {
	return nil
}

// PanicRequest is defined in the .def file
type PanicRequest struct {
}

// Validate returns an error if any of the fields have bad values
func (m *PanicRequest) Validate() error {
	return nil
}

// PanicResponse is defined in the .def file
type PanicResponse struct {
}

// Validate returns an error if any of the fields have bad values
func (m *PanicResponse) Validate() error {
	return nil
}
