// Code generated by jrpc. DO NOT EDIT.

package handler

import (
	context "context"
	http "net/http"

	"github.com/jakewright/home-automation/libraries/go/errors"
	"github.com/jakewright/home-automation/libraries/go/request"
	"github.com/jakewright/home-automation/libraries/go/response"
	"github.com/jakewright/home-automation/libraries/go/router"
	"github.com/jakewright/home-automation/libraries/go/slog"
	def "github.com/jakewright/home-automation/service.user/def"
)

// UserRouter wraps router.Router to provide a convenient way to set handlers
type UserRouter struct {
	*router.Router
	GetUser   func(*Request, *def.GetUserRequest) (*def.GetUserResponse, error)
	ListUsers func(*Request, *def.ListUsersRequest) (*def.ListUsersResponse, error)
}

// NewRouter returns a router that is ready to add handlers to
func NewRouter() *UserRouter {
	rr := &UserRouter{
		Router: router.New(),
	}

	rr.Router.Handle("GET", "/user", func(w http.ResponseWriter, r *http.Request) {
		if rr.GetUser == nil {
			slog.Panicf("No handler exists for GET /user")
		}

		body := &def.GetUserRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.GetUser(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	rr.Router.Handle("GET", "/users", func(w http.ResponseWriter, r *http.Request) {
		if rr.ListUsers == nil {
			slog.Panicf("No handler exists for GET /users")
		}

		body := &def.ListUsersRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.ListUsers(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	return rr
}

type Request struct {
	context.Context
	*http.Request
}
