// Code generated by jrpc. DO NOT EDIT.

package lircproxydef

import (
	context "context"
	"testing"

	taxi "github.com/jakewright/home-automation/libraries/go/taxi"
)

// LircProxyService is the public interface of this service
type LircProxyService interface {
	SendOnce(ctx context.Context, body *SendOnceRequest) *SendOnceFuture
}

// SendOnceFuture represents an in-flight SendOnce request
type SendOnceFuture struct {
	done <-chan struct{}
	rsp  *SendOnceResponse
	err  error
}

// Wait blocks until the response is ready
func (f *SendOnceFuture) Wait() (*SendOnceResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// Client makes requests to this service
type Client struct {
	dispatcher taxi.Dispatcher
}

// Compile-time assertion that the client implements the interface
var _ LircProxyService = (*Client)(nil)

// NewClient returns a new client
func NewClient(dispatcher taxi.Dispatcher) *Client {
	return &Client{
		dispatcher: dispatcher,
	}
}

// SendOnce dispatches an RPC to the service
func (c *Client) SendOnce(ctx context.Context, body *SendOnceRequest) *SendOnceFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "POST",
		URL:    "http://lirc-proxy/send-once",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &SendOnceFuture{
		done: done,
		rsp:  &SendOnceResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// MockClient can be used in tests
type MockClient struct {
	dispatcher *taxi.MockClient
}

// Compile-time assertion that the mock client implements the interface
var _ LircProxyService = (*MockClient)(nil)

// NewMockClient returns a new mock client
func NewMockClient(ctx context.Context, t *testing.T) *MockClient {
	f := taxi.NewTestFixture(t)

	return &MockClient{
		dispatcher: &taxi.MockClient{Handler: f},
	}
}

// SendOnce dispatches an RPC to the mock client
func (c *MockClient) SendOnce(ctx context.Context, body *SendOnceRequest) *SendOnceFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "POST",
		URL:    "http://lirc-proxy/send-once",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &SendOnceFuture{
		done: done,
		rsp:  &SendOnceResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}
