// Code generated by jrpc. DO NOT EDIT.

package handler

import (
	context "context"

	"github.com/jakewright/home-automation/libraries/go/bootstrap"
	router "github.com/jakewright/home-automation/libraries/go/router"
	taxi "github.com/jakewright/home-automation/libraries/go/taxi"
	def "github.com/jakewright/home-automation/services/scene/def"
)

type handler interface {
	CreateScene(ctx context.Context, body *def.CreateSceneRequest) (*def.CreateSceneResponse, error)
	ReadScene(ctx context.Context, body *def.ReadSceneRequest) (*def.ReadSceneResponse, error)
	ListScenes(ctx context.Context, body *def.ListScenesRequest) (*def.ListScenesResponse, error)
	DeleteScene(ctx context.Context, body *def.DeleteSceneRequest) (*def.DeleteSceneResponse, error)
	SetScene(ctx context.Context, body *def.SetSceneRequest) (*def.SetSceneResponse, error)
}

// NewRouter creates a new router for the service
func NewRouter(svc *bootstrap.Service, h handler) *router.Router {
	r := router.New(svc)

	r.RegisterHandler("POST", "/scenes", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.CreateSceneRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.CreateScene(ctx, body)
	})

	r.RegisterHandler("GET", "/scene", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.ReadSceneRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.ReadScene(ctx, body)
	})

	r.RegisterHandler("GET", "/scenes", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.ListScenesRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.ListScenes(ctx, body)
	})

	r.RegisterHandler("DELETE", "/scene", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.DeleteSceneRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.DeleteScene(ctx, body)
	})

	r.RegisterHandler("POST", "/scene/set", func(ctx context.Context, decode taxi.Decoder) (interface{}, error) {
		body := &def.SetSceneRequest{}
		if err := decode(body); err != nil {
			return nil, err
		}

		if err := body.Validate(); err != nil {
			return nil, err
		}

		return h.SetScene(ctx, body)
	})

	return r
}
