// Code generated by jrpc. DO NOT EDIT.

package dmxdef

import (
	context "context"
	"testing"

	taxi "github.com/jakewright/home-automation/libraries/go/taxi"
)

// DMXService is the public interface of this service
type DMXService interface {
	GetMegaParProfile(ctx context.Context, body *GetMegaParProfileRequest) *GetMegaParProfileFuture
	UpdateMegaParProfile(ctx context.Context, body *UpdateMegaParProfileRequest) *UpdateMegaParProfileFuture
}

// GetMegaParProfileFuture represents an in-flight GetMegaParProfile request
type GetMegaParProfileFuture struct {
	done <-chan struct{}
	rsp  *MegaParProfileResponse
	err  error
}

// Wait blocks until the response is ready
func (f *GetMegaParProfileFuture) Wait() (*MegaParProfileResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// UpdateMegaParProfileFuture represents an in-flight UpdateMegaParProfile request
type UpdateMegaParProfileFuture struct {
	done <-chan struct{}
	rsp  *MegaParProfileResponse
	err  error
}

// Wait blocks until the response is ready
func (f *UpdateMegaParProfileFuture) Wait() (*MegaParProfileResponse, error) {
	<-f.done
	return f.rsp, f.err
}

// Client makes requests to this service
type Client struct {
	dispatcher taxi.Dispatcher
}

// Compile-time assertion that the client implements the interface
var _ DMXService = (*Client)(nil)

// NewClient returns a new client
func NewClient(dispatcher taxi.Dispatcher) *Client {
	return &Client{
		dispatcher: dispatcher,
	}
}

// GetMegaParProfile dispatches an RPC to the service
func (c *Client) GetMegaParProfile(ctx context.Context, body *GetMegaParProfileRequest) *GetMegaParProfileFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://dmx/mega-par-profile",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetMegaParProfileFuture{
		done: done,
		rsp:  &MegaParProfileResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// UpdateMegaParProfile dispatches an RPC to the service
func (c *Client) UpdateMegaParProfile(ctx context.Context, body *UpdateMegaParProfileRequest) *UpdateMegaParProfileFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "PATCH",
		URL:    "http://dmx/mega-par-profile",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &UpdateMegaParProfileFuture{
		done: done,
		rsp:  &MegaParProfileResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(ftr.rsp)
	}()

	return ftr
}

// MockClient can be used in tests
type MockClient struct {
	dispatcher *taxi.MockClient
}

// Compile-time assertion that the mock client implements the interface
var _ DMXService = (*MockClient)(nil)

// NewMockClient returns a new mock client
func NewMockClient(ctx context.Context, t *testing.T) *MockClient {
	f := taxi.NewTestFixture(t)

	return &MockClient{
		dispatcher: &taxi.MockClient{Handler: f},
	}
}

// GetMegaParProfile dispatches an RPC to the mock client
func (c *MockClient) GetMegaParProfile(ctx context.Context, body *GetMegaParProfileRequest) *GetMegaParProfileFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "GET",
		URL:    "http://dmx/mega-par-profile",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &GetMegaParProfileFuture{
		done: done,
		rsp:  &MegaParProfileResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}

// UpdateMegaParProfile dispatches an RPC to the mock client
func (c *MockClient) UpdateMegaParProfile(ctx context.Context, body *UpdateMegaParProfileRequest) *UpdateMegaParProfileFuture {
	taxiFtr := c.dispatcher.Dispatch(ctx, &taxi.RPC{
		Method: "PATCH",
		URL:    "http://dmx/mega-par-profile",
		Body:   body,
	})

	done := make(chan struct{})
	ftr := &UpdateMegaParProfileFuture{
		done: done,
		rsp:  &MegaParProfileResponse{},
	}

	go func() {
		defer close(done)
		ftr.err = taxiFtr.DecodeResponse(&ftr.rsp)
	}()

	return ftr
}
