// Code generated by jrpc. DO NOT EDIT.

package handler

import (
	context "context"
	http "net/http"

	"github.com/jakewright/home-automation/libraries/go/errors"
	"github.com/jakewright/home-automation/libraries/go/request"
	"github.com/jakewright/home-automation/libraries/go/response"
	"github.com/jakewright/home-automation/libraries/go/router"
	"github.com/jakewright/home-automation/libraries/go/slog"
	def "github.com/jakewright/home-automation/service.dmx/def"
)

// DMXRouter wraps router.Router to provide a convenient way to set handlers
type DMXRouter struct {
	*router.Router
	GetDevice    func(*Request, *def.GetDeviceRequest) (*def.GetDeviceResponse, error)
	UpdateDevice func(*Request, *def.UpdateDeviceRequest) (*def.UpdateDeviceResponse, error)
}

// NewRouter returns a router that is ready to add handlers to
func NewRouter() *DMXRouter {
	rr := &DMXRouter{
		Router: router.New(),
	}

	rr.Router.Handle("GET", "/device", func(w http.ResponseWriter, r *http.Request) {
		if rr.GetDevice == nil {
			slog.Panicf("No handler exists for GET /device")
		}

		body := &def.GetDeviceRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.GetDevice(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	rr.Router.Handle("PATCH", "/device", func(w http.ResponseWriter, r *http.Request) {
		if rr.UpdateDevice == nil {
			slog.Panicf("No handler exists for PATCH /device")
		}

		body := &def.UpdateDeviceRequest{}
		if err := request.Decode(r, body); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to decode request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		if err := body.Validate(); err != nil {
			err = errors.Wrap(err, errors.ErrBadRequest, "failed to validate request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		req := &Request{
			Context: r.Context(),
			Request: r,
		}

		rsp, err := rr.UpdateDevice(req, body)
		if err != nil {
			err = errors.WithMessage(err, "failed to handle request")
			slog.Error(err)
			response.WriteJSON(w, err)
			return
		}

		response.WriteJSON(w, rsp)
	})

	return rr
}

type Request struct {
	context.Context
	*http.Request
}
